Trace,Diagonals,Matrix Power

In [2]:
import numpy as np

matrix_A=np.array([[3,4,5],[9,2,7],[13,12,15]])
trace=np.trace(matrix_A)
diagonal=np.diagonal(matrix_A)

#A^5,A^10
matrix_A5=np.linalg.matrix_power(matrix_A,5)
matrix_A10=np.linalg.matrix_power(matrix_A,10)

print("Trace:",trace)
print("Diagonal",diagonal)
print("A^5",matrix_A5)
print("A^10",matrix_A10)

Trace: 20
Diagonal [ 3  2 15]
A^5 [[1543376 1193984 1712656]
 [2148256 1660768 2383040]
 [4883472 3777664 5418896]]
A^10 [[13310700390912 10295535585280 14769288545792]
 [18520830687744 14325458060288 20550346026496]
 [42115449722368 32575379257344 46730465899008]]


Upper Triangular,Lower Triangular

In [3]:
upper_triangular=np.triu(matrix_A)
lower_triangular=np.tril(matrix_A)

print("Upper :",upper_triangular)
print("Lower: ",lower_triangular)

Upper : [[ 3  4  5]
 [ 0  2  7]
 [ 0  0 15]]
Lower:  [[ 3  0  0]
 [ 9  2  0]
 [13 12 15]]
