Broadcasting

In [3]:
import numpy as np

#Broadcasting conditions
#->Equal rows
#->Equal columns

A=np.array([[1,2,3],[4,5,6]])
B=np.array([4,5,8])
C=np.array([2,3])

print(np.add(A,B))
#print(np.add(A,C))->No equal rows or columns

#Reshaping C for broadcasting
C=C.reshape((2,1))
print(np.add(A,C))

[[ 5  7 11]
 [ 8 10 14]]
[[3 4 5]
 [7 8 9]]


Projection of Vectors

In [5]:
a=np.array([3,4,9])
b=np.array([2,-5,-4])

#Projection of vector A onto B
p=(np.dot(a,b)/np.dot(b,b))*b
print(p)

[-2.22222222  5.55555556  4.44444444]


Cross,Outer,Kronecker Product

In [6]:
v1=np.array([3,9,12])
v2=np.array([19,-2,0])

m1=np.array([[3,4,5,8],[4,5,9,3]])
m2=np.array([[13,14,25,32],[90,23,41,20]])

cross=np.cross(v1,v2)
outer=np.outer(m1,m2)
kronecker=np.kron(m1,m2)

print("Cross Product: ",cross)
print("Outer Product: ",outer)
print("Kronecker Product: ",kronecker)


Cross Product:  [  24  228 -177]
Outer Product:  [[ 39  42  75  96 270  69 123  60]
 [ 52  56 100 128 360  92 164  80]
 [ 65  70 125 160 450 115 205 100]
 [104 112 200 256 720 184 328 160]
 [ 52  56 100 128 360  92 164  80]
 [ 65  70 125 160 450 115 205 100]
 [117 126 225 288 810 207 369 180]
 [ 39  42  75  96 270  69 123  60]]
Kronecker Product:  [[ 39  42  75  96  52  56 100 128  65  70 125 160 104 112 200 256]
 [270  69 123  60 360  92 164  80 450 115 205 100 720 184 328 160]
 [ 52  56 100 128  65  70 125 160 117 126 225 288  39  42  75  96]
 [360  92 164  80 450 115 205 100 810 207 369 180 270  69 123  60]]
